project:
  type: website

website:
  title: "Faith Satrya"
  navbar:
    right :
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: courses.qmd
        text: Courses
  page-footer: 
    right: "&copy; 2025, Faith Satrya"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    # published-title: "last updated"
    # reference-location: document
    # code-fold: false
    # code-summary: ""
    # fontsize: 1.3em
# change toc (above) to false if you don't want toc by default on site

execute: 
  freeze: auto

